# -*- coding: utf-8 -*-
"""folder splitter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SGmy4CbKJlEylWiXK4-oZrgQnXTY5ynY
"""

from google.colab import drive
drive.mount('/content/drive',)

pip install split-folders

import splitfolders
splitfolders.ratio('/content/drive/MyDrive/Sweet Lime/data', output="/content/drive/MyDrive/Sweet Lime/Output", seed=1337, ratio=(0.7,0.2,0.1))